### ISSUE TITLE
yolov5 模型转换 LLVM ERROR: out of memory

### ISSUE THREAD

**Issue by lswgh** [LynxiTechnology/Lynxi-model-zoo#25]
![捕获](https://user-images.githubusercontent.com/58289826/184828944-d2f852d2-0f99-465f-a590-eab8dec27ca7.PNG)
![捕获1](https://user-images.githubusercontent.com/58289826/184829300-e1e498b6-9796-4689-8bc8-e0ea78eb2120.PNG)
![env](https://user-images.githubusercontent.com/58289826/184829805-40c7f274-b464-4fe5-b813-6d033411e436.jpg)

**Comment by whzz101** [comment]
应该是内存不够，建议加大服务器内存

**Comment by lswgh** [comment]
> 应该是内存不够，建议加大服务器内存
应该不是这个问题,我的服务器系统内存有59G 另外有6个显存为8G 的KA200,我执行这个命令的时候,是过了一秒就报错了

**Comment by lswgh** [comment]
>

**Comment by lswgh** [comment]
> > 应该是内存不够，建议加大服务器内存
> > 应该不是这个问题,我的服务器系统内存有59G 另外有6个显存为8G 的KA200,我执行这个命令的时候,是过了一秒就报错了

另外我指定参数 -t apu 的时候也是报这个
![捕获](https://user-images.githubusercontent.com/58289826/185337576-35add03e-5ddc-4ce9-962a-5445ed4871a2.PNG)
错

**Comment by whzz101** [comment]
如果内存62G编译模型应该是够，yolov5s的编译请按步骤1 2 3 4 依次执行。如果执行成功了后，修改setting.cfg的model_file字段替换成自己训练的模型（一定要是完整的pytorch模型图，不能是只有权重或是torchscript模型），再执行 ./2_convert.sh 即可

**Comment by whzz101** [comment]
如果内存62G编译模型应该是够，yolov5s的编译请按步骤1 2 3 4 依次执行。如果执行成功了后，修改setting.cfg的model_file字段替换成自己训练的模型（一定要是完整的pytorch模型图，不能是只有权重或是torchscript模型），再执行 ./2_convert.sh 即可

**Comment by lswgh** [comment]
> 如果内存62G编译模型应该是够，yolov5s的编译请按步骤1 2 3 4 依次执行。如果执行成功了后，修改setting.cfg的model_file字段替换成自己训练的模型（一定要是完整的pytorch模型图，不能是只有权重或是torchscript模型），再执行 ./2_convert.sh 即可
感谢回答,原因找到了,应该是环境和转换工具的问题
![捕获](https://user-images.githubusercontent.com/58289826/185733797-00734955-e500-433c-b925-9c766b6add48.PNG)

![捕获1](https://user-images.githubusercontent.com/58289826/185733800-5cc58511-367f-4c06-9404-db64b6468412.PNG)
